services:
  neo4j:
    image: neo4j:5.26.2
    container_name: gr_neo4j
    ports:
      - '7474:7474' # HTTP interface
      - '7687:7687' # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/morpheus4j # Replace with your desired username and password
    volumes:
      - neo4j_data:/data

  qdrant:
    image: qdrant/qdrant
    container_name: gr_qdrant
    ports:
      - '6333:6333' # Qdrant REST API port
    volumes:
      - qdrant_storage:/qdrant/storage

  # Ollama for running open source models
  ollama:
    image: ollama/ollama:latest
    container_name: gr_ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama_models:/root/.ollama

volumes:
  neo4j_data:
  qdrant_storage:
  ollama_models:
  # unstructured_cache:
